[ROOrthodox_exp]
Abbreviation=ROOrtExp
Description=Biblia Ortodoxă Română
DataPath=./modules/texts/ztext/roorthodox_exp/
ModDrv=zText
SourceType=OSIS
Lang=ro
Encoding=UTF-8
CompressType=ZIP
BlockType=BOOK
Versification=Orthodox
OSISVersion=2.1.1
Version=0.1
About=Build experimental generat din OSIS. Unele pasaje pot fi mapate greșit din cauza nepotrivirilor de versificare.
DistributionLicense=Copyrighted
TextSource=OSIS XML din repository-ul proiectului
